### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by GabrielJie** [zfergus/fenics-topopt#1]
Hi, zfergus.

I have download your codes, and try to run it. However, one problem is shown as:
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~/shared/fenics-topopt-master/bridge.py in <module>
      7 import numpy as np
      8 
----> 9 from topopt.gui import GUI
     10 import topopt.boundary_conditions
     11 from topopt.solver import Solver

~/shared/fenics-topopt-master/topopt/gui.py in <module>
      6 
      7 
----> 8 from utils import xy_to_id, id_to_xy
      9 
     10 

ModuleNotFoundError: No module named 'utils'

In actual, I can find the file 'utils' in topopt. What is the main reason for this problem ?

**Comment by zfergus** [comment]
Hi Gabriel,

The error is most likely: the TopOpt package was not set up correctly, so Python cannot find the file if the path is anything other than what I was using when programming (probably the structure directory). 

I have continued to develop the TopOpt library (an early version is in this repo) in my spare time. I have been sitting on it for a while, but it will probably be a while before I can finish the release features I want (general meshes (including 3D) and more physical optimization problems and solvers). Rather than waiting and possibly never finishing it, I have decided to go ahead and make the library publically available (https://github.com/zfergus/topopt). It is in a good state right now but has limited features. Specifically, it only supports compliance minimization with linear elasticity on a 2D regular grid using NLopt's MMA optimizer.

I think I resolved your exact problem a while ago. If you can, try out TopOpt and let me know how it goes.

**Comment by GabrielJie** [comment]
Hi zfergus,

Thanks for your reply.

Based on your suggestions, I have resovled the above problem.

In last two years, my main research foucses on the field of topology optimization, refer to my personal website "https://gabrieljie.wixsite.com/jiegao". Recently, I have started a research topic that utilizing FEniCS into Top-opt. Based on the features of FEniCS, my previous codes can be slim and efficiency, and also can be extended other physcial problems using FEniCS easily. In actal, I have encountered many problems, when I starting this topic. In my previous works just for top-opt, I have employed the Matlab platform in Windows operation system. As far as this research topic with FEniCS, I want to continue to use the Windows operation system, because I am unfamiliar with the Linux or Mac. In order to run the fenicsproject in windows, I have installed the docker in windows and developed a container using FEniCS images, which can work as a platform to develop using Jupyter notebook to realize the topic (Topology optimization using FeniCS, like your codes). the detailed flowchart can refer to "https://fenics.readthedocs.io/projects/containers/en/latest/jupyter.html". However, many problems have occured, like the "nlopt" cannot be importted in the notebook, and it is not easy to develop the program.

Could you give me some recommendations about this topic that using FEniCS in Top-opt? In actual, I am very curious about your work platform. How do you do as far as this stopic?

**Comment by zfergus** [comment]
The goal of this project was originally to do the topology optimization using FEniCS entirely, but we instead settled for a simple implementation of topology optimization with a secondary elasticity simulation of the results using FEniCS.

I agree that using FEniCS in topology optimization would enable an easier interface for developing new topology optimization methods. I am excited about the idea, but unfortunately, I have not had the time to implement a true FEniCS topology optimization library.

One difficulty is using the adjoint method with FEniCS, but I found the [Dolphin Adjoint library](http://www.dolfin-adjoint.org/en/release/) does exactly that. They even have [examples](http://www.dolfin-adjoint.org/en/release/documentation/poisson-topology/poisson-topology.html) of topology optimization(unfortunately, none for elasticity).

When I was using FEniCS for this project I resorted to using the docker image because of compilation difficulties on macOS. I have since been able to compile it but with significant effort (probably even more on Windows).

As for running my TopOpt library make sure all the dependencies are installed (e.g. to install NLopt for Python you can use `pip install nlopt`). All the requirements are in `requirements.txt`

**Comment by GabrielJie** [comment]
Thanks for your reply and recommendations.

Based on my recent work, I feel that it is not an easy to implement. Anyway, I will have a try. Meanwhile, how do you feel about the computational efficiency when top-opt use the FEniCS, particularly for 3D. Maybe, how long does each iteration step needs?

Wish we can have a cooperation about this topic.

With best regards.

**Comment by zfergus** [comment]
I haven't used FEniCS in 3D very much, but from what I remember in 2D it wasn't too slow. If you bad to iterate (as in topology optimization) I'm not sure how well it will perform. I think there are ways to speed up FEniCS, though. 

I would be interested in how your implementation goes. Feel free to email me.

**Comment by GabrielJie** [comment]
Ok,

Thanks for your help.

With best regards,
Jie.
